import{S as p}from"./assets/vendor-CgTBfC_f.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function c(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(e){if(e.ep)return;e.ep=!0;const i=c(e);fetch(e.href,i)}})();const f=[{preview:"./img/img-1.webp",original:"./img/img-1-large.webp",description:"Brain Storm"},{preview:"./img/img-2.webp",original:"./img/img-2-large.webp",description:"Bulb"},{preview:"./img/img-3.webp",original:"./img/img-3-large.webp",description:"Phone"},{preview:"./img/img-4.webp",original:"./img/img-4-large.webp",description:"Loft Office"},{preview:"./img/img-5.webp",original:"./img/img-5-large.webp",description:"Coworking"},{preview:"./img/img-6.webp",original:"./img/img-6-large.webp",description:"Office"},{preview:"./img/img-7.webp",original:"./img/img-7-large.webp",description:"Notebook"},{preview:"./img/img-8.webp",original:"./img/img-8-large.webp",description:"Working Woman"},{preview:"./img/img-9.webp",original:"./img/img-9-large.webp",description:"Meeting"}],g=document.querySelector("ul.gallery");if(g){const t=f.map(o=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o.original}">
          <img class="gallery-image" 
               src="${o.preview}" 
               data-source="${o.original}" 
               alt="${o.description}" />
        </a>
      </li>`).join("");g.innerHTML=t,new p(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!0})}else console.error("Галерея не знайдена!");const r={email:"",message:""},a=document.querySelector(".feedback-form"),s="feedback-form-state";a.addEventListener("input",t=>{t.target.name in r&&(r[t.target.name]=t.target.value,localStorage.setItem(s,JSON.stringify(r)))});const m=localStorage.getItem(s);m&&(Object.assign(r,JSON.parse(m)),a.elements.email.value=r.email,a.elements.message.value=r.message);a.addEventListener("submit",t=>{if(t.preventDefault(),!r.email.trim()||!r.message.trim()){alert("Fill please all fields");return}console.log(r),localStorage.removeItem(s),r.email="",r.message="",a.reset()});
//# sourceMappingURL=index.js.map
